const checked = '2026-09-18';

export const curatedDestinations = {
  lisbon: {
    city: 'Lisbon',
    videoUrl: 'https://www.youtube.com/watch?v=17bI_Y91E_8',
    message: 'A short list for city views, history, and walking. Prices are published reference prices, not live quotes.',
    places: [
      {
        id: 'lisbon-castle',
        name: 'Castelo de São Jorge',
        category: 'Landmark',
        description: 'Explore the castle and ramparts above Lisbon. A good choice for city views and history.',
        tryThis: 'Walk the ramparts and explore the castle grounds.',
        price: '€17 adult',
        priceNote: `Published adult admission, checked ${checked}. Discounts and conditions vary.`,
        imageUrl: 'https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://castelodesaojorge.pt/como-visitar/escolher-o-bilhete/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Castelo+de+Sao+Jorge+Lisbon',
      },
      {
        id: 'lisbon-oceanario',
        name: 'Oceanário de Lisboa',
        category: 'Aquarium',
        description: 'Explore marine habitats at the aquarium in Parque das Nações.',
        tryThis: 'Visit the aquarium exhibitions; allow around 1½–2 hours.',
        price: '€25–€29 adult',
        priceNote: `Published adult admission varies by time slot, checked ${checked}.`,
        imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://oceanario.pt/planear-visita/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Oceanario+de+Lisboa',
      },
      {
        id: 'lisbon-comercio',
        name: 'Praça do Comércio',
        category: 'Walking',
        description: 'A riverside square with arcades and a view of the Tagus. Combine it with a walk through Baixa.',
        tryThis: 'Take a self-guided riverside walk and photograph the square.',
        price: 'No ticket for the public square',
        priceNote: 'Food, tours, nearby museums, and the arch viewpoint cost extra.',
        imageUrl: 'https://images.unsplash.com/photo-1513688778135-c8950e2e8e03?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.visitportugal.com/en/NR/exeres/64BE2716-BB28-4041-8E05-594DF1BAAE95',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Praca+do+Comercio+Lisbon',
      },
      {
        id: 'lisbon-luzia',
        name: 'Miradouro de Santa Luzia',
        category: 'Viewpoint',
        description: 'A viewpoint over Alfama and the Tagus. Add it to a walk around the old neighbourhood.',
        tryThis: 'Enjoy the view and explore the surrounding Alfama streets.',
        price: 'Public viewpoint; check local access',
        priceNote: 'No ticket price is listed by the city. Guided tours and refreshments are extra.',
        imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.lisboa.pt/en/points-of-interest/space-detail?cHash=8a01fff1febdff2e4a6f7ef5ea76aadf&tx_espacos_espacodetail%5Baction%5D=detail&tx_espacos_espacodetail%5Bcontroller%5D=Espaco&tx_espacos_espacodetail%5Bespaco%5D=338',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Miradouro+de+Santa+Luzia+Lisbon',
      },
      {
        id: 'lisbon-belem',
        name: 'Torre de Belém',
        category: 'Landmark',
        description: 'Iconic 16th-century fortress on the bank of the Tagus celebrating Portuguese maritime discoveries.',
        tryThis: 'Climb the spiral stairs to the upper terrace and visit the nearby historic bakery.',
        price: '€9 adult',
        priceNote: 'Discounts available with Lisboa Card and for students.',
        imageUrl: 'https://images.unsplash.com/photo-1588774069410-84ae30757c8e?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.torrebelem.gov.pt/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Belem+Tower+Lisbon',
      },
    ],
  },
  jaipur: {
    city: 'Jaipur',
    videoUrl: 'https://www.youtube-nocookie.com/embed/Q3y6uM_iX2k',
    message: 'Explore the royal palaces, astronomical wonders, and historic forts of the Pink City.',
    places: [
      {
        id: 'jaipur-hawa-mahal',
        name: 'Hawa Mahal',
        category: 'Landmark',
        description: 'Distinctive five-storey pink sandstone palace featuring 953 intricate honeycomb windows.',
        tryThis: 'Visit in early morning for beautiful lighting and photograph from Wind View Cafe across the street.',
        price: '₹200 foreign / ₹50 Indian',
        priceNote: 'Composite ticket options available for multiple monuments.',
        imageUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80',
        videoUrl: 'https://www.youtube-nocookie.com/embed/p1oPsqwQ_bM',
        sourceUrl: 'https://www.tourism.rajasthan.gov.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Hawa+Mahal+Jaipur',
      },
      {
        id: 'jaipur-amber-fort',
        name: 'Amber Palace (Amer Fort)',
        category: 'Palace',
        description: 'Majestic hilltop fort known for its artistic Hindu-style elements and Sheesh Mahal mirror work.',
        tryThis: 'Take a guided heritage walk and catch the evening light and sound show.',
        price: '₹500 foreign / ₹100 Indian',
        priceNote: 'Audio guides available at entrance.',
        imageUrl: 'https://images.unsplash.com/photo-1603288967396-8575a28cb20d?w=800&auto=format&fit=crop&q=80',
        videoUrl: 'https://www.youtube-nocookie.com/embed/yQeP_sH6Bw0',
        sourceUrl: 'https://www.tourism.rajasthan.gov.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Amber+Fort+Jaipur',
      },
      {
        id: 'jaipur-city-palace',
        name: 'City Palace',
        category: 'Palace',
        description: 'A magnificent blend of Rajput, Mughal, and European architecture in the heart of the Old City.',
        tryThis: 'Explore the museum galleries, royal textiles, and the famous peacock courtyard.',
        price: '₹700 foreign / ₹300 Indian',
        priceNote: 'Royal Grandeur tour tickets cost extra.',
        imageUrl: 'https://images.unsplash.com/photo-1600100397608-f010f443a925?w=800&auto=format&fit=crop&q=80',
        videoUrl: 'https://www.youtube-nocookie.com/embed/hJq1z6RjFv4',
        sourceUrl: 'https://royaljaipur.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=City+Palace+Jaipur',
      },
      {
        id: 'jaipur-jantar-mantar',
        name: 'Jantar Mantar',
        category: 'Landmark',
        description: 'UNESCO World Heritage site featuring the world’s largest stone sundial and astronomical instruments.',
        tryThis: 'Hire an authorized audio guide to understand the fascinating celestial geometry.',
        price: '₹200 foreign / ₹50 Indian',
        priceNote: 'Discounts for students with valid ID.',
        imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80',
        videoUrl: 'https://www.youtube-nocookie.com/embed/Vb8T_2Yy5zM',
        sourceUrl: 'http://www.jantarmantar.org/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Jantar+Mantar+Jaipur',
      },
      {
        id: 'jaipur-nahargarh',
        name: 'Nahargarh Fort',
        category: 'Viewpoint',
        description: 'Perched on the edge of the Aravalli Hills, offering breathtaking panoramic sunset views over Jaipur.',
        tryThis: 'Catch the sunset from the rooftop terrace and explore the Madhavendra Bhawan.',
        price: '₹200 foreign / ₹50 Indian',
        priceNote: 'Vehicle parking charges apply at top.',
        imageUrl: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&auto=format&fit=crop&q=80',
        videoUrl: 'https://www.youtube-nocookie.com/embed/4y5WqfW6X8I',
        sourceUrl: 'https://www.tourism.rajasthan.gov.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Nahargarh+Fort+Jaipur',
      },
    ],
  },
  bangalore: {
    city: 'Bangalore',
    videoUrl: 'https://www.youtube.com/watch?v=7b7pS66_4xM',
    message: 'Discover lush botanical parks, royal heritage palaces, and modern garden city life.',
    places: [
      {
        id: 'blr-palace',
        name: 'Bangalore Palace',
        category: 'Palace',
        description: 'Tudor-style royal estate with fortified towers, wood carvings, and lush gardens inspired by Windsor Castle.',
        tryThis: 'Take the audio tour to explore royal memorabilia, hunting trophies, and 19th-century paintings.',
        price: '₹460 foreign / ₹230 Indian',
        priceNote: 'Camera and photography ticket fees apply separately.',
        imageUrl: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://karnatakatourism.org/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Bangalore+Palace',
      },
      {
        id: 'blr-lalbagh',
        name: 'Lalbagh Botanical Garden',
        category: 'Garden',
        description: 'Historic 240-acre botanical haven founded by Hyder Ali, featuring an iconic 19th-century Glass House.',
        tryThis: 'Stroll around the central lake and visit during the famous biannual flower show.',
        price: '₹30 adult',
        priceNote: 'Free entry during morning fitness hours (6 AM – 9 AM).',
        imageUrl: 'https://images.unsplash.com/photo-1588416936097-41850ab3d86d?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://karnatakatourism.org/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Lalbagh+Botanical+Garden+Bangalore',
      },
      {
        id: 'blr-cubbon',
        name: 'Cubbon Park',
        category: 'Garden',
        description: 'The green lung of Bangalore spanning 300 acres with shaded avenues, bamboo groves, and statues.',
        tryThis: 'Rent a bicycle, enjoy a morning jog, or read under the massive rain trees.',
        price: 'Free entry',
        priceNote: 'Public park open from sunrise to sunset.',
        imageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://karnatakatourism.org/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Cubbon+Park+Bangalore',
      },
      {
        id: 'blr-tipu',
        name: 'Tipu Sultan’s Summer Palace',
        category: 'Landmark',
        description: 'Ornate two-storey wooden palace constructed entirely from teakwood with carved pillars and arches.',
        tryThis: 'Admire the Indo-Islamic floral frescoes and visit the ground-floor historical museum.',
        price: '₹100 foreign / ₹20 Indian',
        priceNote: 'Archaeological Survey of India site.',
        imageUrl: 'https://images.unsplash.com/photo-1600100397608-f010f443a925?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://asi.nic.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Tipu+Sultans+Summer+Palace+Bangalore',
      },
      {
        id: 'blr-commercial',
        name: 'Commercial Street & Brigade Road',
        category: 'Walking',
        description: 'Vibrant shopping and street food district buzzing with cafes, silk boutiques, and street vendors.',
        tryThis: 'Sample authentic Mysore pak sweets and South Indian filter coffee between shopping stops.',
        price: 'Free entry',
        priceNote: 'Food and retail purchases vary.',
        imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://karnatakatourism.org/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Commercial+Street+Bangalore',
      },
    ],
  },
  mumbai: {
    city: 'Mumbai',
    videoUrl: 'https://www.youtube.com/watch?v=k5q4H_9f95o',
    message: 'Experience the bustling coastal energy, colonial monuments, and vibrant boulevards of Mumbai.',
    places: [
      {
        id: 'mum-gateway',
        name: 'Gateway of India',
        category: 'Landmark',
        description: 'Iconic 26-metre basalt arch monument overlooking Mumbai Harbour, built in 1924.',
        tryThis: 'Walk along the waterfront promenade and take a ferry towards Elephanta Caves.',
        price: 'Free entry',
        priceNote: 'Ferry tickets to Elephanta are purchased separately.',
        imageUrl: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.maharashtratourism.gov.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Gateway+of+India+Mumbai',
      },
      {
        id: 'mum-marine-drive',
        name: 'Marine Drive (Queen’s Necklace)',
        category: 'Walking',
        description: '3.6-kilometre C-shaped coastal boulevard offering magnificent sea breezes and skyline views.',
        tryThis: 'Take an evening stroll at sunset and enjoy street snacks like bhelpuri at Chowpatty.',
        price: 'Free entry',
        priceNote: 'Public promenade open 24/7.',
        imageUrl: 'https://images.unsplash.com/photo-1566552881560-0be862a7c445?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.maharashtratourism.gov.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Marine+Drive+Mumbai',
      },
      {
        id: 'mum-csmt',
        name: 'Chhatrapati Shivaji Maharaj Terminus (CSMT)',
        category: 'Landmark',
        description: 'UNESCO-listed Victorian Gothic revival railway station and active architectural icon.',
        tryThis: 'Photograph the illuminated facade at night and tour the heritage museum inside.',
        price: 'Free exterior / ₹200 museum tour',
        priceNote: 'Active railway station; train tickets required for platform entry.',
        imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://whc.unesco.org/en/list/945',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Chhatrapati+Shivaji+Maharaj+Terminus+Mumbai',
      },
      {
        id: 'mum-elephanta',
        name: 'Elephanta Caves',
        category: 'Culture',
        description: 'Historic island rock-cut cave temples dedicated to Shiva dating back to the 5th century.',
        tryThis: 'Admire the 20-foot high Trimurti sculpture in Cave 1.',
        price: '₹600 foreign / ₹40 Indian',
        priceNote: 'Ferry from Gateway of India is ₹260 return.',
        imageUrl: 'https://images.unsplash.com/photo-1600100397608-f010f443a925?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://asi.nic.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Elephanta+Caves+Mumbai',
      },
      {
        id: 'mum-bandra',
        name: 'Bandra Bandstand & Fort',
        category: 'Viewpoint',
        description: 'Picturesque rocky coastline with views of the Bandra-Worli Sea Link and Portuguese fort.',
        tryThis: 'Watch waves crash against the rocks and explore Bandra’s boutique cafes nearby.',
        price: 'Free entry',
        priceNote: 'Public park and historical viewpoint.',
        imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.maharashtratourism.gov.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Bandra+Fort+Mumbai',
      },
    ],
  },
  delhi: {
    city: 'Delhi',
    videoUrl: 'https://www.youtube.com/watch?v=Jm3jM9B19qg',
    message: 'Explore ancient monuments, monumental Mughal tombs, and bustling cultural centers.',
    places: [
      {
        id: 'del-qutub',
        name: 'Qutub Minar',
        category: 'Landmark',
        description: '73-metre red sandstone minaret dating to 1192 and UNESCO World Heritage complex.',
        tryThis: 'Check out the mysterious 1,600-year-old rust-resistant Iron Pillar in the courtyard.',
        price: '₹600 foreign / ₹40 Indian',
        priceNote: 'Online booking discounts available.',
        imageUrl: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://asi.nic.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Qutub+Minar+Delhi',
      },
      {
        id: 'del-humayun',
        name: 'Humayun’s Tomb',
        category: 'Landmark',
        description: 'Exquisite 16th-century Mughal garden tomb that inspired the architectural design of the Taj Mahal.',
        tryThis: 'Stroll through the Persian-style Charbagh water gardens at golden hour.',
        price: '₹600 foreign / ₹40 Indian',
        priceNote: 'Audio tours available at entrance.',
        imageUrl: 'https://images.unsplash.com/photo-1608958435020-e8a7109ba809?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://asi.nic.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Humayuns+Tomb+Delhi',
      },
      {
        id: 'del-india-gate',
        name: 'India Gate',
        category: 'Walking',
        description: 'Prominent war memorial arch on Kartavya Path with beautiful evening fountains and lawns.',
        tryThis: 'Enjoy an evening walk along the illuminated boulevard and taste local street delicacies.',
        price: 'Free entry',
        priceNote: 'Public national monument open 24/7.',
        imageUrl: 'https://images.unsplash.com/photo-1597042780415-3735ff8bb36b?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://delhitourism.gov.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=India+Gate+Delhi',
      },
      {
        id: 'del-red-fort',
        name: 'Red Fort (Lal Qila)',
        category: 'Palace',
        description: 'Historic fortress in Old Delhi that served as the primary residence of Mughal emperors.',
        tryThis: 'Explore the Diwan-i-Aam, Diwan-i-Khas, and the museum galleries.',
        price: '₹600 foreign / ₹50 Indian',
        priceNote: 'Light and sound show tickets extra.',
        imageUrl: 'https://images.unsplash.com/photo-1585130401366-fe05a8d813c4?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://asi.nic.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Red+Fort+Delhi',
      },
      {
        id: 'del-lotus',
        name: 'Lotus Temple',
        category: 'Culture',
        description: 'Striking lotus-shaped Baháʼí House of Worship open to people of all faiths for silent reflection.',
        tryThis: 'Experience the peaceful silence inside the marble prayer hall and wander the 9 surrounding ponds.',
        price: 'Free entry',
        priceNote: 'Shoes must be checked at the entrance counter.',
        imageUrl: 'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.bahai.in/lotus-temple/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Lotus+Temple+Delhi',
      },
    ],
  },
  goa: {
    city: 'Goa',
    videoUrl: 'https://www.youtube.com/watch?v=0hO15R5m3a4',
    message: 'Relax on sun-kissed beaches, explore heritage Portuguese quarters, and discover coastal forts.',
    places: [
      {
        id: 'goa-bom-jesus',
        name: 'Basilica of Bom Jesus',
        category: 'Culture',
        description: 'UNESCO World Heritage Baroque church in Old Goa holding the sacred relics of St. Francis Xavier.',
        tryThis: 'Admire the 16th-century gilded altar and Portuguese colonial architecture.',
        price: 'Free entry',
        priceNote: 'Modest attire required inside the church.',
        imageUrl: 'https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.goatourism.gov.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Basilica+of+Bom+Jesus+Goa',
      },
      {
        id: 'goa-aguada',
        name: 'Aguada Fort & Lighthouse',
        category: 'Landmark',
        description: '17th-century Portuguese fortress and 4-storey lighthouse standing guard over the Arabian Sea.',
        tryThis: 'Walk the upper ramparts for sweeping ocean panoramas, especially at sunset.',
        price: '₹50 adult',
        priceNote: 'Parking charges extra.',
        imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.goatourism.gov.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Fort+Aguada+Goa',
      },
      {
        id: 'goa-palolem',
        name: 'Palolem Beach',
        category: 'Beach',
        description: 'Crescent-shaped white sand beach in South Goa fringed with coconut palms and colourful beach shacks.',
        tryThis: 'Take a dolphin-spotting boat trip and enjoy fresh seafood at the beachfront shacks.',
        price: 'Free entry',
        priceNote: 'Boat trips and kayak rentals ₹300–₹800.',
        imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.goatourism.gov.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Palolem+Beach+Goa',
      },
      {
        id: 'goa-dudhsagar',
        name: 'Dudhsagar Waterfalls',
        category: 'Outdoors',
        description: 'Spectacular four-tiered waterfall on the Mandovi River plunging 310 metres amidst dense jungle.',
        tryThis: 'Take an exhilarating 4x4 jeep safari through the Bhagwan Mahavir Wildlife Sanctuary.',
        price: '₹50 forest fee + ₹500 jeep safari',
        priceNote: 'Jeep safari booking through the local operators union.',
        imageUrl: 'https://images.unsplash.com/photo-1546548970-71785318a17b?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.goatourism.gov.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Dudhsagar+Falls+Goa',
      },
      {
        id: 'goa-fontainhas',
        name: 'Fontainhas (Latin Quarter)',
        category: 'Walking',
        description: 'Picturesque historic heritage precinct in Panaji with brightly painted Portuguese-style villas.',
        tryThis: 'Take a walking photography tour and stop at a heritage bakery for Bebinca cake.',
        price: 'Free walking',
        priceNote: 'Guided heritage walking tours available.',
        imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.goatourism.gov.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Fontainhas+Panjim+Goa',
      },
    ],
  },
  tokyo: {
    city: 'Tokyo',
    videoUrl: 'https://www.youtube.com/watch?v=6DZkX8xTsp4',
    message: 'Immerse in neon-lit crossings, ancient shrines, tranquil gardens, and skyline views.',
    places: [
      {
        id: 'tokyo-sensoji',
        name: 'Senso-ji Temple',
        category: 'Culture',
        description: 'Tokyo’s oldest and most significant Buddhist temple, located in the historic Asakusa district.',
        tryThis: 'Walk through the Kaminarimon Thunder Gate and browse traditional snacks along Nakamise-dori.',
        price: 'Free entry',
        priceNote: 'Small donations for incense and omikuji fortunes.',
        imageUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.senso-ji.jp/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Senso-ji+Tokyo',
      },
      {
        id: 'tokyo-shibuya',
        name: 'Shibuya Crossing & Hachiko',
        category: 'Walking',
        description: 'The world’s busiest pedestrian intersection where thousands cross simultaneously under neon billboards.',
        tryThis: 'Watch the pedestrian surge from the Shibuya Sky observation deck or crossing cafes.',
        price: 'Free street crossing / ¥2,000 for Shibuya Sky',
        priceNote: 'Book Shibuya Sky tickets online in advance.',
        imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.gotokyo.org/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Shibuya+Crossing+Tokyo',
      },
      {
        id: 'tokyo-meiji',
        name: 'Meiji Jingu Shrine',
        category: 'Culture',
        description: 'Serene Shinto shrine set within a lush 170-acre forest of over 120,000 evergreen trees in Shibuya.',
        tryThis: 'Pass through the towering cedar Torii gates and write a wish on an Ema wooden plaque.',
        price: 'Free entry',
        priceNote: '¥500 for the Inner Garden.',
        imageUrl: 'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.meijijingu.or.jp/en/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Meiji+Shrine+Tokyo',
      },
      {
        id: 'tokyo-skytree',
        name: 'Tokyo Skytree',
        category: 'Viewpoint',
        description: 'A 634-metre broadcasting tower offering breathtaking 360-degree panoramas across Greater Tokyo.',
        tryThis: 'Walk across the glass floor section on the Tembo Deck at 350m.',
        price: '¥2,100–¥3,100 adult',
        priceNote: 'Prices vary by deck levels and peak weekend times.',
        imageUrl: 'https://images.unsplash.com/photo-1538935732373-f7a495fea3f6?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.tokyo-skytree.jp/en/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Tokyo+Skytree',
      },
      {
        id: 'tokyo-shinjuku',
        name: 'Shinjuku Gyoen National Garden',
        category: 'Garden',
        description: 'Blends traditional Japanese landscape, English formal, and French geometric garden styles.',
        tryThis: 'Relax on the open lawns, visit the greenhouse, and enjoy the tea house.',
        price: '¥500 adult',
        priceNote: 'Valid ID required for student discounts.',
        imageUrl: 'https://images.unsplash.com/photo-1578637387939-43c525550085?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.env.go.jp/garden/shinjukugyoen/english/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Shinjuku+Gyoen+Tokyo',
      },
    ],
  },
  paris: {
    city: 'Paris',
    videoUrl: 'https://www.youtube.com/watch?v=AQ6GmpKo5L8',
    message: 'Explore world-class art collections, romantic river walks, and landmark architecture.',
    places: [
      {
        id: 'paris-eiffel',
        name: 'Eiffel Tower',
        category: 'Landmark',
        description: 'Gustave Eiffel’s 1889 iron masterpiece and the defining symbol of the City of Light.',
        tryThis: 'Ascend to the summit at twilight to watch the hourly sparkle lights display.',
        price: '€11.80 (stairs) – €29.40 (summit lift)',
        priceNote: 'Advance online reservation strongly recommended.',
        imageUrl: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.toureiffel.paris/en',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Eiffel+Tower+Paris',
      },
      {
        id: 'paris-louvre',
        name: 'Louvre Museum',
        category: 'Museum',
        description: 'The world’s largest art museum, home to the Mona Lisa, Venus de Milo, and Winged Victory.',
        tryThis: 'Enter via the Carrousel du Louvre underground entrance to beat the main pyramid queue.',
        price: '€22 adult',
        priceNote: 'Free for under 18s and EU residents under 26.',
        imageUrl: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.louvre.fr/en',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Louvre+Museum+Paris',
      },
      {
        id: 'paris-orsay',
        name: 'Musée d’Orsay',
        category: 'Museum',
        description: 'Former Beaux-Arts railway station holding the world’s finest collection of Impressionist masterpieces.',
        tryThis: 'Admire Van Gogh, Monet, and Renoir paintings, then look out through the giant station clock.',
        price: '€16 adult',
        priceNote: 'Combined museum tickets available.',
        imageUrl: 'https://images.unsplash.com/photo-1584448141569-69f342da535c?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.musee-orsay.fr/en',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Musee+dOrsay+Paris',
      },
      {
        id: 'paris-sacre-coeur',
        name: 'Sacré-Cœur Basilica & Montmartre',
        category: 'Viewpoint',
        description: 'Romano-Byzantine basilica perched atop Montmartre hill offering stunning views across Paris.',
        tryThis: 'Climb the dome stairs for panoramic views and explore the Place du Tertre artists square.',
        price: 'Free basilica entry / €8 dome climb',
        priceNote: 'Dome climb requires walking 300 steps (no lift).',
        imageUrl: 'https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'http://www.sacre-coeur-montmartre.com/english/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Sacre+Coeur+Paris',
      },
      {
        id: 'paris-seine',
        name: 'Seine River Walk & Île de la Cité',
        category: 'Walking',
        description: 'Romantic stroll along the UNESCO-listed riverbanks, past bouquinistes booksellers and Pont Neuf.',
        tryThis: 'Cross Pont des Arts and view Notre-Dame Cathedral from Square Jean XXIII.',
        price: 'Free walking / €17 for boat cruises',
        priceNote: 'River cruises depart regularly from Pont Neuf.',
        imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://en.parisinfo.com/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Ile+de+la+Cite+Paris',
      },
    ],
  },
  london: {
    city: 'London',
    videoUrl: 'https://www.youtube.com/watch?v=0hY5xR4lYkQ',
    message: 'Discover iconic royal landmarks, ancient fortresses, world-class museums, and Thames walks.',
    places: [
      {
        id: 'lon-tower',
        name: 'Tower of London & Tower Bridge',
        category: 'Landmark',
        description: 'Nearly 1,000-year-old royal fortress housing the Crown Jewels and Yeoman Warders.',
        tryThis: 'Join a free Yeoman Warder guided tour and walk across the Tower Bridge glass walkway.',
        price: '£34.80 adult',
        priceNote: 'Book online in advance for discounts.',
        imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.hrp.org.uk/tower-of-london/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Tower+of+London',
      },
      {
        id: 'lon-museum',
        name: 'British Museum',
        category: 'Museum',
        description: 'World-renowned museum dedicated to human history, art, and culture beneath the Great Court glass roof.',
        tryThis: 'See the Rosetta Stone, Parthenon Sculptures, and Egyptian mummies.',
        price: 'Free general entry',
        priceNote: 'Special exhibitions require paid tickets. Booking free timed entry is recommended.',
        imageUrl: 'https://images.unsplash.com/photo-1584448141569-69f342da535c?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.britishmuseum.org/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=British+Museum+London',
      },
      {
        id: 'lon-big-ben',
        name: 'Big Ben & Palace of Westminster',
        category: 'Landmark',
        description: 'The iconic Gothic revival Houses of Parliament and the world’s most famous clock tower along the Thames.',
        tryThis: 'Walk across Westminster Bridge for classic photo angles and hear the famous chime.',
        price: 'Free exterior / £25–£32 interior tours',
        priceNote: 'Parliament tours can be booked in advance.',
        imageUrl: 'https://images.unsplash.com/photo-1529655683826-aba9b3e77383?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.parliament.uk/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Big+Ben+London',
      },
      {
        id: 'lon-eye',
        name: 'South Bank & London Eye',
        category: 'Walking',
        description: 'Lively cultural promenade featuring street performers, food markets, and the 135-metre observation wheel.',
        tryThis: 'Ride the London Eye for 360° skyline vistas and browse the Southbank Centre Book Market.',
        price: 'Free walk / £38 London Eye ticket',
        priceNote: 'Discounts available when booking online in advance.',
        imageUrl: 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.londoneye.com/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=London+Eye',
      },
      {
        id: 'lon-hyde-park',
        name: 'Hyde Park & Kensington Gardens',
        category: 'Garden',
        description: 'Sprawling 350-acre Royal Park with the Serpentine Lake, Diana Memorial Fountain, and Kensington Palace.',
        tryThis: 'Rent a pedal boat on the Serpentine and visit the Serpentine Gallery.',
        price: 'Free park entry',
        priceNote: 'Kensington Palace state apartments require tickets.',
        imageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.royalparks.org.uk/parks/hyde-park',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Hyde+Park+London',
      },
    ],
  },
  newyork: {
    city: 'New York',
    videoUrl: 'https://www.youtube.com/watch?v=MtCMtC50gwY',
    message: 'Explore world-famous skyline observatories, Central Park walks, and legendary cultural landmarks.',
    places: [
      {
        id: 'nyc-central-park',
        name: 'Central Park',
        category: 'Garden',
        description: 'An 843-acre urban oasis with winding paths, lakes, bridges, and iconic movie locations in Manhattan.',
        tryThis: 'Walk across Bow Bridge, visit Bethesda Terrace, and rent a rowboat at the Loeb Boathouse.',
        price: 'Free entry',
        priceNote: 'Boat rentals and zoo admissions are extra.',
        imageUrl: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.centralparknyc.org/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Central+Park+New+York',
      },
      {
        id: 'nyc-statue-liberty',
        name: 'Statue of Liberty & Ellis Island',
        category: 'Landmark',
        description: 'Colossal neoclassical copper sculpture on Liberty Island, a universal symbol of freedom.',
        tryThis: 'Take the morning ferry from Battery Park to explore both the monument and immigration museum.',
        price: '$24.50 adult',
        priceNote: 'Crown access requires advance reservation.',
        imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.nps.gov/stli/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Statue+of+Liberty+New+York',
      },
      {
        id: 'nyc-empire-state',
        name: 'Empire State Building',
        category: 'Viewpoint',
        description: '102-story Art Deco skyscraper in Midtown Manhattan with 360-degree open-air observation decks.',
        tryThis: 'Visit the 86th floor open-air observatory at dusk to watch the city transition from day to night.',
        price: '$44 adult',
        priceNote: '102nd floor top deck upgrade available.',
        imageUrl: 'https://images.unsplash.com/photo-1546436836-07a91091f160?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.esbnyc.com/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Empire+State+Building+New+York',
      },
      {
        id: 'nyc-highline',
        name: 'The High Line & Chelsea Market',
        category: 'Walking',
        description: '1.45-mile elevated linear park on a historic freight rail line above Manhattan’s West Side.',
        tryThis: 'Stroll past public art installations and grab gourmet lobster rolls or tacos at Chelsea Market.',
        price: 'Free public park',
        priceNote: 'Food and market vendor purchases vary.',
        imageUrl: 'https://images.unsplash.com/photo-1541336032412-2048a678540d?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.thehighline.org/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=The+High+Line+New+York',
      },
    ],
  },
  rome: {
    city: 'Rome',
    videoUrl: 'https://www.youtube.com/watch?v=0hY1jN2qE8k',
    message: 'Walk through ancient amphitheaters, baroque fountains, and monumental piazzas.',
    places: [
      {
        id: 'rome-colosseum',
        name: 'Colosseum & Roman Forum',
        category: 'Landmark',
        description: 'The largest ancient amphitheatre ever built, holding gladiator spectacles for 50,000 spectators.',
        tryThis: 'Walk through the arena floor and climb Palatine Hill for views over the Forum ruins.',
        price: '€18 adult',
        priceNote: 'Timed entry ticket includes Colosseum, Roman Forum, and Palatine Hill.',
        imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://parcocolosseo.it/en/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Colosseum+Rome',
      },
      {
        id: 'rome-trevi',
        name: 'Trevi Fountain (Fontana di Trevi)',
        category: 'Walking',
        description: 'Dramatic 18th-century Baroque fountain depicting Oceanus surrounded by tritons and seahorses.',
        tryThis: 'Toss a coin with your right hand over your left shoulder to ensure a return trip to Rome.',
        price: 'Free public fountain',
        priceNote: 'Best visited at early morning or late night to avoid crowds.',
        imageUrl: 'https://images.unsplash.com/photo-1525874684015-58379d421a52?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.turismoroma.it/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Trevi+Fountain+Rome',
      },
      {
        id: 'rome-pantheon',
        name: 'The Pantheon',
        category: 'Landmark',
        description: 'Best-preserved monument of ancient Rome, featuring a giant unreinforced concrete dome with an open oculus.',
        tryThis: 'Stand beneath the central oculus to watch the sunbeam light up the marble interior.',
        price: '€5 adult',
        priceNote: 'Advance booking required on weekends.',
        imageUrl: 'https://images.unsplash.com/photo-1542820229-081e0c12af0b?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.pantheonroma.com/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Pantheon+Rome',
      },
      {
        id: 'rome-vatican',
        name: 'Vatican Museums & Sistine Chapel',
        category: 'Museum',
        description: 'Massive papal art collection featuring Michelangelo’s breathtaking frescoes on the Sistine Chapel ceiling.',
        tryThis: 'Walk the Raphael Rooms and gaze up at the Creation of Adam in the Sistine Chapel.',
        price: '€20 adult',
        priceNote: 'Online booking required to skip queues.',
        imageUrl: 'https://images.unsplash.com/photo-1548625361-195feee15f9b?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.museivaticani.va/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Vatican+Museums+Rome',
      },
    ],
  },
  dubai: {
    city: 'Dubai',
    videoUrl: 'https://www.youtube.com/watch?v=IdejM6wCkxA',
    message: 'Experience futuristic architecture, desert dunes, and world-record observatories.',
    places: [
      {
        id: 'dub-burj-khalifa',
        name: 'Burj Khalifa',
        category: 'Viewpoint',
        description: 'The world’s tallest building standing at 828 metres with multi-level outdoor observation decks.',
        tryThis: 'Visit the 124th & 125th floor observation decks and watch the Dubai Fountain show below.',
        price: 'AED 179 adult',
        priceNote: 'Prime sunset hour tickets cost extra.',
        imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.burjkhalifa.ae/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Burj+Khalifa+Dubai',
      },
      {
        id: 'dub-fountain',
        name: 'The Dubai Mall & Fountain',
        category: 'Walking',
        description: 'The world’s largest destination for shopping and entertainment with a giant choreographed fountain system.',
        tryThis: 'Watch the evening fountain show set to light and music every 30 minutes from the waterfront promenade.',
        price: 'Free public fountain show',
        priceNote: 'Dubai Mall attractions like the Aquarium are ticketed.',
        imageUrl: 'https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://thedubaimall.com/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Dubai+Fountain',
      },
      {
        id: 'dub-creek',
        name: 'Dubai Creek & Old Souks',
        category: 'Culture',
        description: 'Historic saltwater inlet where traditional wooden abra boats ferry passengers between Deira Gold and Spice Souks.',
        tryThis: 'Take a traditional 1 AED abra boat ride across the creek and bargain for aromatic spices.',
        price: 'AED 1 abra ride',
        priceNote: 'Shopping and guided heritage tours vary.',
        imageUrl: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.visitdubai.com/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Dubai+Creek',
      },
      {
        id: 'dub-miracle-garden',
        name: 'Dubai Miracle Garden',
        category: 'Garden',
        description: 'The world’s largest natural flower garden showcasing over 150 million blooms crafted into arches and sculptures.',
        tryThis: 'Walk through the heart-shaped flower passage and photograph the floral Emirates A380 airplane.',
        price: 'AED 95 adult',
        priceNote: 'Open seasonally from November to April.',
        imageUrl: 'https://images.unsplash.com/photo-1580674285054-bed31e145f59?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.dubaimiraclegarden.com/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Dubai+Miracle+Garden',
      },
    ],
  },
  singapore: {
    city: 'Singapore',
    videoUrl: 'https://www.youtube.com/watch?v=P_q3BdrFsLI',
    message: 'Explore futuristic supertrees, biodiverse cloud domes, and vibrant street hawker food.',
    places: [
      {
        id: 'sg-gardens',
        name: 'Gardens by the Bay',
        category: 'Garden',
        description: 'Award-winning horticultural wonderland featuring iconic Supertrees, Cloud Forest, and Flower Dome.',
        tryThis: 'Walk the mist-filled Cloud Forest mountain and watch the nightly Garden Rhapsody light show.',
        price: 'S$32 adult for dual conservatories',
        priceNote: 'Outdoor garden grounds and light show are free.',
        imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.gardensbythebay.com.sg/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Gardens+by+the+Bay+Singapore',
      },
      {
        id: 'sg-marina-bay',
        name: 'Marina Bay Sands SkyPark',
        category: 'Viewpoint',
        description: 'Iconic cantilevered observation deck perched 57 levels above Singapore with panoramic harbor vistas.',
        tryThis: 'Catch the sunset from the SkyPark observation deck and watch the Spectra light show below.',
        price: 'S$32 adult',
        priceNote: 'Infinity pool is exclusive to hotel guests.',
        imageUrl: 'https://images.unsplash.com/photo-1506351421178-63b52a2d2562?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.marinabaysands.com/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Marina+Bay+Sands+Singapore',
      },
      {
        id: 'sg-chinatown',
        name: 'Chinatown & Buddha Tooth Relic Temple',
        category: 'Culture',
        description: 'Vibrant heritage district with four-storey Tang-style temple and bustling Maxwell Food Centre.',
        tryThis: 'Visit the serene rooftop garden at the temple and savor Michelin Bib Gourmand Hainanese chicken rice.',
        price: 'Free temple entry',
        priceNote: 'Hawker meals average S$5–S$8.',
        imageUrl: 'https://images.unsplash.com/photo-1565967511849-76a60a516170?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.visitsingapore.com/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Buddha+Tooth+Relic+Temple+Singapore',
      },
      {
        id: 'sg-sentosa',
        name: 'Sentosa Island & Palawan Beach',
        category: 'Beach',
        description: 'Resort island offering white sand beaches, coastal suspension bridge, and entertainment parks.',
        tryThis: 'Cross the suspension bridge to the southernmost point of Continental Asia.',
        price: 'Free beach entry',
        priceNote: 'Sentosa Express monorail is S$4.',
        imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.sentosa.com.sg/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Palawan+Beach+Sentosa',
      },
    ],
  },
  bali: {
    city: 'Bali',
    videoUrl: 'https://www.youtube.com/watch?v=dfs6gDqZq5E',
    message: 'Discover emerald rice terraces, cliffside sea temples, and tropical coastal beauty.',
    places: [
      {
        id: 'bali-tanah-lot',
        name: 'Tanah Lot Temple',
        category: 'Landmark',
        description: 'Ancient Hindu pilgrimage temple perched on a dramatic wave-swept offshore rock formation.',
        tryThis: 'Visit during sunset for iconic silhouette photographs against the Indian Ocean.',
        price: 'IDR 60,000 foreign adult',
        priceNote: 'Parking charges apply at entrance.',
        imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.indonesia.travel/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Tanah+Lot+Bali',
      },
      {
        id: 'bali-tegalalang',
        name: 'Tegallalang Rice Terraces',
        category: 'Outdoors',
        description: 'Iconic stepped green rice paddies in Ubud carved into the valley using ancient Subak irrigation.',
        tryThis: 'Trek through the valley paths in early morning mist and try the jungle swing.',
        price: 'IDR 25,000 entry',
        priceNote: 'Jungle swing and photo nest activities cost extra.',
        imageUrl: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.indonesia.travel/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Tegalalang+Rice+Terrace+Bali',
      },
      {
        id: 'bali-uluwatu',
        name: 'Uluwatu Temple & Kecak Dance',
        category: 'Culture',
        description: 'Cliffside sea temple standing 70 metres above crashing waves on Bali’s southwestern tip.',
        tryThis: 'Watch the spellbinding sunset Kecak Fire Dance performance in the clifftop amphitheater.',
        price: 'IDR 50,000 temple / IDR 150,000 dance',
        priceNote: 'Sarongs provided free at entrance.',
        imageUrl: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.indonesia.travel/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Uluwatu+Temple+Bali',
      },
      {
        id: 'bali-monkey-forest',
        name: 'Sacred Monkey Forest Sanctuary',
        category: 'Wildlife',
        description: 'Lush natural jungle sanctuary in Ubud housing over 1,000 Balinese long-tailed macaques and mossy temples.',
        tryThis: 'Walk along shaded wooden bridges and admire ancient banyan roots enveloping stone shrines.',
        price: 'IDR 80,000 adult',
        priceNote: 'Secure loose belongings before entering.',
        imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://monkeyforestubud.com/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Sacred+Monkey+Forest+Sanctuary+Ubud',
      },
    ],
  },
  agra: {
    city: 'Agra',
    videoUrl: 'https://www.youtube.com/watch?v=F3G6_mI6Qrk',
    message: 'Marvel at timeless Mughal marble architecture and historic riverside imperial fortresses.',
    places: [
      {
        id: 'agra-taj-mahal',
        name: 'Taj Mahal',
        category: 'Landmark',
        description: 'World-renowned ivory-white marble mausoleum on the Yamuna River, commissioned by Shah Jahan in 1632.',
        tryThis: 'Experience the soft pink hues of sunrise over the reflecting pool and main marble dome.',
        price: '₹1100 foreign / ₹50 Indian',
        priceNote: 'Main mausoleum interior ticket is ₹200 extra. Closed on Fridays.',
        imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://www.tajmahal.gov.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Taj+Mahal+Agra',
      },
      {
        id: 'agra-fort',
        name: 'Agra Fort',
        category: 'Palace',
        description: 'Massive red sandstone fortress and UNESCO World Heritage site that served as the main Mughal royal seat.',
        tryThis: 'Look through the marble arches of the Musamman Burj for a distant view of the Taj Mahal.',
        price: '₹650 foreign / ₹50 Indian',
        priceNote: 'Discount available if visited on the same day as Taj Mahal.',
        imageUrl: 'https://images.unsplash.com/photo-1585130401366-fe05a8d813c4?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://asi.nic.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Agra+Fort',
      },
      {
        id: 'agra-mehtab-bagh',
        name: 'Mehtab Bagh (Moonlight Garden)',
        category: 'Viewpoint',
        description: 'Charbagh garden complex located directly across the Yamuna River offering tranquil, crowd-free views.',
        tryThis: 'Capture reflection photographs of the Taj Mahal at sunset across the river.',
        price: '₹300 foreign / ₹25 Indian',
        priceNote: 'Best lighting during the late afternoon.',
        imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://asi.nic.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Mehtab+Bagh+Agra',
      },
      {
        id: 'agra-fatehpur',
        name: 'Fatehpur Sikri',
        category: 'Culture',
        description: 'Emperor Akbar’s magnificent 16th-century red sandstone capital city featuring the towering Buland Darwaza.',
        tryThis: 'Walk through the grand courtyard and tie a thread for wishes at the tomb of Salim Chishti.',
        price: '₹610 foreign / ₹50 Indian',
        priceNote: 'Located 36 km west of Agra.',
        imageUrl: 'https://images.unsplash.com/photo-1600100397608-f010f443a925?w=800&auto=format&fit=crop&q=80',
        sourceUrl: 'https://asi.nic.in/',
        mapUrl: 'https://www.google.com/maps/search/?api=1&query=Fatehpur+Sikri',
      },
    ],
  },
};

function normalizeKey(str = '') {
  return str.toLowerCase().replace(/[^a-z0-9]/g, '');
}

function findCityData(destination = '') {
  const normalized = normalizeKey(destination);
  for (const [key, data] of Object.entries(curatedDestinations)) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return data;
    }
  }

  // Generic dynamic curated dataset for any other entered destination
  const formattedCity = destination.trim().replace(/^./, c => c.toUpperCase());
  return {
    city: formattedCity,
    videoUrl: 'https://www.youtube.com/watch?v=17bI_Y91E_8',
    message: `Curated highlights, landmarks, and sights for ${formattedCity}.`,
    places: [
      {
        id: `${normalizeKey(formattedCity)}-historic-center`,
        name: `${formattedCity} Historic Old Town`,
        category: 'Walking',
        description: `Explore the cobblestone avenues, architectural heritage, and lively central plazas of ${formattedCity}.`,
        tryThis: 'Take a self-guided walking tour and discover local artisan shops and cafes.',
        price: 'Free public access',
        priceNote: 'Museums, guided tours, and tastings cost extra.',
        imageUrl: 'https://images.unsplash.com/photo-1513688778135-c8950e2e8e03?w=800&auto=format&fit=crop&q=80',
        sourceUrl: `https://www.google.com/search?q=${encodeURIComponent(formattedCity + ' tourism')}`,
        mapUrl: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(formattedCity + ' City Center')}`,
      },
      {
        id: `${normalizeKey(formattedCity)}-royal-monument`,
        name: `${formattedCity} Grand Landmark & Fortress`,
        category: 'Landmark',
        description: `Historic fortress and architectural icon that served as the defensive stronghold and pride of ${formattedCity}.`,
        tryThis: 'Walk the historic ramparts and check out the panoramic views of the city skyline.',
        price: 'Check admission price',
        priceNote: 'Published admission fees apply at entrance. Discounts for students and seniors.',
        imageUrl: 'https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=800&auto=format&fit=crop&q=80',
        sourceUrl: `https://www.google.com/search?q=${encodeURIComponent(formattedCity + ' landmarks')}`,
        mapUrl: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(formattedCity + ' Landmark')}`,
      },
      {
        id: `${normalizeKey(formattedCity)}-city-viewpoint`,
        name: `${formattedCity} Panoramic Viewpoint`,
        category: 'Viewpoint',
        description: `Scenic vantage point offering panoramic vistas over ${formattedCity} and surrounding landscapes.`,
        tryThis: 'Visit during golden hour or sunset for spectacular photo opportunities.',
        price: 'Free viewpoint access',
        priceNote: 'Refreshments, transport, and cable cars cost extra.',
        imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&auto=format&fit=crop&q=80',
        sourceUrl: `https://www.google.com/search?q=${encodeURIComponent(formattedCity + ' viewpoints')}`,
        mapUrl: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(formattedCity + ' Viewpoint')}`,
      },
      {
        id: `${normalizeKey(formattedCity)}-central-museum`,
        name: `${formattedCity} Heritage Museum & Gallery`,
        category: 'Museum',
        description: `Showcases the rich art, historical artifacts, and cultural traditions of the ${formattedCity} region.`,
        tryThis: 'Explore the permanent exhibits and check for seasonal cultural displays.',
        price: 'Check admission price',
        priceNote: 'Admission fees vary by exhibition and concession status.',
        imageUrl: 'https://images.unsplash.com/photo-1584448141569-69f342da535c?w=800&auto=format&fit=crop&q=80',
        sourceUrl: `https://www.google.com/search?q=${encodeURIComponent(formattedCity + ' museums')}`,
        mapUrl: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(formattedCity + ' Museum')}`,
      },
      {
        id: `${normalizeKey(formattedCity)}-city-park`,
        name: `${formattedCity} Botanical Gardens & Park`,
        category: 'Garden',
        description: `Peaceful green retreat featuring landscaped gardens, ancient trees, and walking paths.`,
        tryThis: 'Enjoy a leisurely stroll or picnic under the shade of the park trees.',
        price: 'Free entry',
        priceNote: 'Special glasshouses or events may require admission.',
        imageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&auto=format&fit=crop&q=80',
        sourceUrl: `https://www.google.com/search?q=${encodeURIComponent(formattedCity + ' botanical garden')}`,
        mapUrl: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(formattedCity + ' Park')}`,
      },
    ],
  };
}

export async function getSuggestions(destination) {
  const cityData = findCityData(destination);

  // Map places to match both places and items format for full backwards compatibility
  const mappedPlaces = cityData.places.map(place => ({
    ...place,
    activity: place.tryThis,
    source: place.sourceUrl,
  }));

  return {
    city: cityData.city,
    location: cityData.city,
    videoUrl: cityData.videoUrl,
    message: cityData.message,
    source: 'Curated travel guide',
    fetchedAt: checked,
    places: mappedPlaces,
    items: mappedPlaces,
  };
}


